//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneroPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public Block()
        {
            this.BlockRewards = new HashSet<BlockReward>();
        }
    
        public int Id { get; set; }
    
        public virtual ICollection<BlockReward> BlockRewards { get; set; }
    }
}
