//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneroPool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockReward
    {
        public int Id { get; set; }
        public long Shares { get; set; }
        public double Value { get; set; }
        public int BlockId { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Miner Miner { get; set; }
    }
}
